# Generated by Django 3.2.19 on 2023-06-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
