# Generated by Django 3.2.19 on 2023-06-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0002_alter_bankaccount_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='zipcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
