# Generated by Django 3.2.19 on 2023-06-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banktransaction', '0002_auto_20230623_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
